version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=Daddine123
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: sleheddine/tp-foyer-5.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.show-sql": true,
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "server.port": 8089,
        "server.servlet.context-path": "/tpfoyer",
      }'
    stdin_open: true
    tty: true

volumes:
  db:
