version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allows empty password; for production, set a root password
      MYSQL_DATABASE: tpfoyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    image: docker-myapp:latest  # Updated image name
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8089:8089  # Changed to use port 8089 to avoid conflicts
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",  # Changed localhost to mysqldb
          "spring.datasource.username": "root",
          "spring.datasource.password": "",  # Set this to your MySQL root password if you have one
          "spring.jpa.show-sql": true,
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
